package data.scripts.campaign.items;


import com.fs.starfarer.api.EveryFrameScript;
import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.*;
import com.fs.starfarer.api.campaign.impl.items.BaseSpecialItemPlugin;
import com.fs.starfarer.api.fleet.FleetMemberAPI;
import com.fs.starfarer.api.ui.TooltipMakerAPI;
import com.fs.starfarer.api.util.Misc;
import data.hullmods.aEP_CruiseMissileCarrier;
import data.scripts.campaign.entity.aEP_CruiseMissileEntityPlugin;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

import static com.fs.starfarer.api.impl.campaign.ids.MemFlags.FLEET_IGNORED_BY_OTHER_FLEETS;
import static combat.util.aEP_DataTool.txt;


public class aEP_CruiseMissile extends BaseSpecialItemPlugin
{
  protected List<String> tags = new ArrayList<String>();
  CargoAPI cargo;

  public static void createMissile(SectorEntityToken token, float angle) {
    CustomCampaignEntityAPI missile = token.getContainingLocation().addCustomEntity(null,
      null,
      "aEP_FSF_CruiseMissile",
      token.getFaction().getId());
    missile.setFacing(angle);
    missile.setContainingLocation(token.getContainingLocation());
    missile.setLocation(token.getLocation().x, token.getLocation().y);
    aEP_CruiseMissileEntityPlugin plugin = (aEP_CruiseMissileEntityPlugin) missile.getCustomPlugin();
    plugin.setVariantId("aEP_CM");
  }

  @Override
  public void init(CargoStackAPI stack) {
    super.init(stack);
    cargo = stack.getCargo();
    String param = spec.getParams();
    if (!param.isEmpty()) {
      for (String tag : param.split(",")) {
        tag = tag.trim();
        if (tag.isEmpty()) continue;
        tags.add(tag);
      }
    }

  }

  @Override
  public void performRightClickAction() {
    boolean useOne = false;
    if (cargo != null && cargo.getFleetData() != null && cargo.getFleetData().getFleet() != null) {
      for(FleetMemberAPI m : Global.getSector().getPlayerFleet().getMembersWithFightersCopy()){
        if(aEP_CruiseMissileCarrier.Companion.getLoadedNum(m) >= 1f){
          aEP_CruiseMissileCarrier.Companion.putLoadedNum(m,0f);
          useOne = true;
          break;
        }
      }
    }


    if (!useOne) {
      Global.getSector().getPlayerFleet().getCargo().addSpecial(new SpecialItemData("aEP_CM", null), 1);
      return;
    }

    /**
     * Adds a custom entity.
     * Use SectorEntityToken.setFixedLocation() or .setCircularOrbit (or setOrbit) to set its location and/or orbit.
     * @param id unique id. autogenerated if null.
     * @param name default name for entity used if this is null
     * @param type id in custom_entities.json
     * @param factionId defaults to "neutral" if not specified
     * @return
     */
    CustomCampaignEntityAPI missile = Global.getSector().getPlayerFleet().getContainingLocation().addCustomEntity(null,
      null,
      "aEP_FSF_CruiseMissile",
      Global.getSector().getPlayerFleet().getFaction().getId());
    missile.getMemoryWithoutUpdate().set(FLEET_IGNORED_BY_OTHER_FLEETS,true);
    missile.setFacing(Global.getSector().getPlayerFleet().getFacing());
    missile.setContainingLocation(Global.getSector().getPlayerFleet().getContainingLocation());
    missile.setLocation(Global.getSector().getPlayerFleet().getLocation().x, Global.getSector().getPlayerFleet().getLocation().y);
    aEP_CruiseMissileEntityPlugin plugin = (aEP_CruiseMissileEntityPlugin) missile.getCustomPlugin();
    plugin.setVariantId("aEP_CM");
  }


  @Override
  public boolean hasRightClickAction() {
    return Global.getSector().getCampaignUI().getCurrentCoreTab() == CoreUITabId.CARGO;
  }

  @Override
  public boolean shouldRemoveOnRightClickAction() {
    return true;
  }

  @Override
  public void createTooltip(TooltipMakerAPI tooltip, boolean expanded, CargoTransferHandlerAPI transferHandler, Object stackSource, boolean useGray) {
    float opad = 10f;

    tooltip.addTitle(getName());

    String design = getDesignType();
    Misc.addDesignTypePara(tooltip, design, opad);

    if (!spec.getDesc().isEmpty()) {
      Color c = Misc.getTextColor();
      tooltip.addPara(spec.getDesc(), c, opad);
    }
    Color c = Misc.getTextColor();
    if (useGray) c = Misc.getGrayColor();
    tooltip.addPara(txt("CruiseMissileItem01"), c, opad);

    int loadedNum = 0;
    if (cargo != null && cargo.getFleetData() != null && cargo.getFleetData().getFleet() != null) {
      for(FleetMemberAPI m : Global.getSector().getPlayerFleet().getMembersWithFightersCopy()){
        if(aEP_CruiseMissileCarrier.Companion.getLoadedNum(m) >= 1f){
          loadedNum += 1;
        }
      }
    }

    if (loadedNum < 1)
      tooltip.addPara(txt("CruiseMissileItem02"), Color.red, opad);
    else
      tooltip.addPara(txt("CruiseMissileItem03"), opad, Color.white, Color.yellow, loadedNum + "");


    if (Global.getSector().getCampaignUI().getCurrentCoreTab() != CoreUITabId.CARGO)
      tooltip.addPara(txt("CruiseMissileItem04"), Color.red, opad);

  }


}

